version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: mediapp_postgres
    environment:
      POSTGRES_USER: zrodrigolimaz
      POSTGRES_PASSWORD: Mediapp2024!Secure
      POSTGRES_DB: meu_app_db
    ports:
      - "5432:5432"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

